export const GET_TRACKERS_SUCCESS = "GET_TRACKERS_SUCCESS";
export const SAVE_TRACKER_SUCCESS = "SAVE_TRACKER_SUCCESS";
export const UPDATE_TRACKER_SUCCESS = "UPDATE_TRACKER_SUCCESS";
export const DELETE_TRACKER_SUCCESS = "DELETE_TRACKER_SUCCESS";

export const GET_MEAL_SUCCESS = "GET_MEAL_SUCCESS";
export const SAVE_MEAL_SUCCESS = "SAVE_MEAL_SUCCESS";
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS";
export const DELETE_MEAL_SUCCESS = "DELETE_MEAL_SUCCESS";

export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS";
export const SAVE_FOOD_SUCCESS = "SAVE_FOOD_SUCCESS";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";